# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."expo-db-stack-app-server" = {
    image = "compose2nix/expo-db-stack-app-server";
    environment = {
      "APP_PORT" = "8082";
      "DATABASE_HOST" = "db";
      # TODO: make more secure with either keys or asking the user to make the password on setup
      "DATABASE_NAME" = "mydatabase"; 
      "DATABASE_PASSWORD" = "mypassword";
      "DATABASE_USER" = "myuser";
      "REACT_NATIVE_PACKAGER_HOSTNAME" = "host.docker.internal";
      "SERVER_IP" = "host.docker.internal";
    };
    ports = [
      "8081:8081/tcp"
      "8082:8082/tcp"
    ];
    dependsOn = [
      "expo-db-stack-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app-server"
      "--network=expo-db-stack_app-network"
    ];
  };
  systemd.services."docker-expo-db-stack-app-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-expo-db-stack_app-network.service"
    ];
    requires = [
      "docker-network-expo-db-stack_app-network.service"
    ];
    partOf = [
      "docker-compose-expo-db-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-expo-db-stack-root.target"
    ];
  };
  virtualisation.oci-containers.containers."expo-db-stack-db" = {
    image = "postgres:14";
    environment = {
      "POSTGRES_DB" = "mydatabase";
      "POSTGRES_PASSWORD" = "mypassword";
      "POSTGRES_USER" = "myuser";
    };
    volumes = [
      "expo-db-stack_postgres_data:/var/lib/postgresql/data:rw"
    ];
    ports = [
      "5432:5432/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U myuser -d mydatabase"
      "--health-interval=10s"
      "--health-retries=5"
      "--health-timeout=5s"
      "--network-alias=db"
      "--network=expo-db-stack_app-network"
    ];
  };
  systemd.services."docker-expo-db-stack-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-expo-db-stack_app-network.service"
      "docker-volume-expo-db-stack_postgres_data.service"
    ];
    requires = [
      "docker-network-expo-db-stack_app-network.service"
      "docker-volume-expo-db-stack_postgres_data.service"
    ];
    partOf = [
      "docker-compose-expo-db-stack-root.target"
    ];
    wantedBy = [
      "docker-compose-expo-db-stack-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-expo-db-stack_app-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f expo-db-stack_app-network";
    };
    script = ''
      docker network inspect expo-db-stack_app-network || docker network create expo-db-stack_app-network --driver=bridge
    '';
    partOf = [ "docker-compose-expo-db-stack-root.target" ];
    wantedBy = [ "docker-compose-expo-db-stack-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-expo-db-stack_postgres_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect expo-db-stack_postgres_data || docker volume create expo-db-stack_postgres_data
    '';
    partOf = [ "docker-compose-expo-db-stack-root.target" ];
    wantedBy = [ "docker-compose-expo-db-stack-root.target" ];
  };

  # Builds
  systemd.services."docker-build-expo-db-stack-app-server" = {
    path = [ pkgs.docker pkgs.git ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutSec = 300;
    };
    script = ''
      cd /home/rafa/Documents/code/scan-containers
      docker build -t compose2nix/expo-db-stack-app-server .
    '';
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-expo-db-stack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
